#!/bin/bash


backup_file=`date +%Y%m%d`
backup_path=/tmp/

for i in `find /data/ -type f -name "*.txt" `
  do
        if [ -f "$i" ];then
                echo "备份文件 $i"
                #使用${i##*/}提取文件名部分，而不是整个文件路径
                cp "${i}" "${backup_path}/${i##*/}_${backup_file}"
        else
                echo "文件$i不存在"
        fi
done
